spring:
  #数据冶理&标准使用的redis配置
  redis:
    host: 172.16.29.60
    port: 6380
    password: ENC(Wlcmq4L+jNeLd0O8Rym9fqOo1ewJMdj0ehzGbVf6fQU=)
    redisson:
      config:
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          # address: "redis://10.189.152.202:31860"
          # password: Liuyj@2022
          subscriptionsPerConnection: 5
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000

  datasource:
    rdcp-ext:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://172.16.29.33:5432/rdcp_ext_qd_gzcp?currentSchema=test&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
      username: ENC(ow4uAAjEcKiszfWdUDJ8O4r/tKpx0pL+)
      password: ENC(mv+m1KiMKN9uw8WNWKNrL62RnsC0Ow43)
      pool-name: HikariCP-rdcp-ext
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认2分钟
      idle-timeout: 120000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1

  devtools:
    restart:
      enabled: false

    # kafka 消费者设置
  kafka:
    bootstrap-servers: 172.16.29.48:9092
    producer:
      retries: 3
      batch-size: 1000
      linger-ms: 5
      buffer-memory: 33554432
      acks: 1
      maxBlock: 1
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      type: SINGLE
    topic:
      cdc: cdc-data
      xds: gove-xds-${spring.profiles.active}
      dolphinScheduler-task: dolphin-schedule-task-${spring.profiles.active}
      intelligence:
        fep-task: frontend-reschedule-test
        tunnel-datasource-change: tunnel-datasource-change-test
        original-structure: original-structure
      fep:
        ## listen
        xds-create: xds-create
        xds-update: xds-update
        upload-tableCount: upload-tableCount
        update-collect-message: update-collect-message
        upload-original-structure: upload-original-structure
        upload-original-table-count: upload-original-table-count
        ## send
        ## tunnel-config-change-${ip}-${port} 按照前置机ip和端口区分
        tunnel-config-change: tunnel-config-change
        ## original-structure-config-${orgCode} 按照系统编码区分
        original-structure-config: original-structure-config
        ## tunnel-schedule-task-${ip}-${port} 按照前置机ip和端口区分
        tunnel-schedule-task: tunnel-schedule-task

  servlet:
    multipart:
      # 文件最大限制
      max-file-size: 1024MB
      # 请求最大限制
      max-request-size: 1024MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0


# 文件上传校验
file:
  upload:
    check:
      switch: 1
      max_file_num: 5
      max_file_size: 1073741824 # 1G；单位是 字节；
      file_suffix: xls;xlsx

# xss 校验
xss:
  urlPatterns: /*
  enabled: true
  excludes: null

# 分页pageHelper
pagehelper:
  auto-runtime-dialect: true
  supportMethodsArguments: true
  params: count=countSql

jasypt:
  encryptor:
    # 配置加密算法
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
      prefix: ENC(
      # 算法识别后缀
      suffix: )


converge:
  filepath: /tmp/file/converge
  backup: /tmp/file/backup


lrhealth:
  converge:
    privateKeyStr: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJAbEE0QLz/lY+W2n6uDPwRoOENMKGIm2OCQYFAewbFz0lnODIKx0NsDXqy2wtsZaSXXYG7wucIHfJrMVIRZEm879jUXLcBL1ijKks7dve+/Mq8N/tWaX65L5AbL6Q81PxJZuAm6ez+7MNKYagoNAGUb3BN7nbfE8MwEoFyVTffJAgMBAAECgYAS3/ian2wQ6nLTO8BeLqqqYRw9dFQ1xvDRORfkZqLoI0uCB8MLu06n4SEdbjLHj+R92GABJ/asu15OyESpsSEAzeCYCig/Ed93IzLN/jbobHiucY+sjY4RvuPFTAuJIQCEmY33Ljj7xZRlbLWOP+4d35Mu9Iv7csN8gA+6k+DEIQJBAODgJQj1uibLnrXbO80DjrSs+O7d+dHcMGdHgz+EigTLBupfcMPfvMEBey/aSlFAuPYqVE4vzym7cfdYT4SMWksCQQCkDQ8E59LJOvERy9GLNri9MDYsi4/B/mIRxxhuEVbEzZXAY0/U9lo47WcfOj9zU+X0CZbdapGPjLH7vR3ltim7AkEAuZA8/2fGdL0R+n8umb6VxAH4aSRDQimwx4j7hS6ZtdrTmhOnufqmh53xSUuYh/QgrQHBD8Pj70v+f10gQQCQgQJAeoc6YYqYuC3q4kTeRGFhyARbYhf3DojmTKrsx0DyEtoOcHx8ou5BYuWGMR+7RnMyfHwxDz1KbPJD+Wc+DlVpgwJAL1+yHvNluA0abhcB2NdVc9JLEiYlqpCk50xsRtbdZzdrYr66INyuEAPX37scmvm55jPPh55GxJ5SlQ4Tw1Iw6w==
    outputPath: C:\\work
    scheduledCron: 0/5 * * * * *
    dataSaveCron: 0/5 * * * * *

datax:
  softpath: D:\\Users\\admin\\Desktop\\datax
  exec: bin/datax.py
  home: D:\\Users\\admin\\Desktop\\datax
  json-path: D:\\Users\\admin\\Desktop\\datax\\job
  execute-number-limit: 0
  collect-multith: 0
  dest-path: D:\\Users\\admin\\Desktop\\datax\\job\\file

file-collect:
  structure-type: csv

xds:
  switch-on: true

