server:
  port: 8018

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # 应用名称
    name: lr-data-rdcp-data-converge
  profiles:
    # 环境配置
    active: local

## ds配置
ds:
  host: http://172.16.29.60:12345/dolphinscheduler/
  token: 727504e58dc2b3f61002fdde0116c064
  switch: true

