server:
  port: 8017

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # 应用名称
    name: lr-data-rdcp-data-converge
  profiles:
    # 环境配置
    active: local

## ds配置
ds:
  host: http://172.16.29.60:12345/dolphinscheduler/
  token: 467313b9cefe7c21d9f5fe9eb1520dd5
  switch: true

