spring:
  datasource:
    rdcp-ext:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://172.16.29.33:5432/rdcp_ext_qd_gzcp?currentSchema=test&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
      username: ENC(ow4uAAjEcKiszfWdUDJ8O4r/tKpx0pL+)
      password: ENC(mv+m1KiMKN9uw8WNWKNrL62RnsC0Ow43)
      pool-name: HikariCP-rdcp-ext

    # kafka 消费者设置
  kafka:
    bootstrap-servers: 172.16.29.48:9092
    topic:
      xds: gove-xds-${spring.profiles.active}
      dolphinScheduler-task: dolphin-schedule-task-${spring.profiles.active}
    consumer:
      group-id: local-profile-12

message:
  sql:
    path: /Users/yinwenbao/gitlab/lr-rd-rdcp-data-converge/script/sql.properties

