server:
  port: 8017

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # 应用名称
    name: lr-data-rdcp-data-converge
  profiles:
    # 环境配置
    active: local

## ds配置
ds:
  host: http://172.16.29.60:12345/dolphinscheduler/
  token: 727504e58dc2b3f61002fdde0116c064
  switch: true

## 消息队列可能的各种消息体key,用StrPool.COMMA(,)分割
message:
  parse:
    operation: op
    prevalue: before
    postvalue: after
    collectTable: table
  ## 执行的操作
    insertOp: c
    updateOp: u
    deleteOp: d
  sql:
    path: D:\sql.properties
    config:
      insert: insert
      update: update
      delete: delete

